export default {
  WEAK_PASSWORD: 'This password is too weak.',
  INVALID_EMAIL: 'This email is invalid',
  EMAIL_IN_USE: 'This email is already in use',
  VALIDATE_EAMIL: 'An email with a verification link has been sent to your email address',
  RESET_PASSWORD: 'An email has been sent to your email address to reset your password.',
  ACCOUNT_DISABLED: 'Sorry! Your account has been disabled.',
  WORNG_COMBINATION: 'Wrong email/password combination.',
  EMAIL_NOT_VARIFIED: 'Your email address is not verified. Please check your email.',
  LOGIN_SUCCESS: 'Login successful!',
  LINK_EXPIRE: 'Your verification link has expired.',
  LINK_INVALID: 'Your verification link is invalid.',
  NO_USER: 'No user is currently signed in.',
  SIGNED_IN: 'You have already signed in',
  POST_MISSING_TITLE: 'Please enter a title for this item',
  POST_SUCCESS: 'You have successfully posted your item',
}